### ISSUE TITLE
Update of IP address reset TTL and proxied/dnsOnly value

### ISSUE THREAD

**Issue by ligol** [mxplusb/cloudflare-sync#5]
Method to reproduce:
Define a specific TTL or set dns only on your config line and wait for an update from cloudlare-sync, all value will be put back to default(TTL : Automatic, Proxied).

Could be nice to keep the old configuration of the line by default or via a flag

**Comment by siennathesane** [comment]
The configuration file is a subset of the JSON payload required for the Cloudflare API, so if you set the values to match whatever you already have configured, it should honor those. I should likely document that behaviour.

**Comment by ligol** [comment]
Oh yes sorry, haven't seen that configuration.

Thanks
