### ISSUE TITLE
Can't compile the binary

### ISSUE THREAD

**Issue by inductor** [mxplusb/cloudflare-sync#7]
I get the following error both on macOS and Docker container(Alpine)
```
./main.go:117:4: undefined: quit
```

Is this because the channel name is not valid here?
https://github.com/mxplusb/cloudflare-sync/blob/master/main.go#L117

```diff
-	<-quit
```

**Comment by siennathesane** [comment]
@inductor this should be fixed in the most recent commits, can you please verify? I'm going to close this as fixed but please feel free to reopen it if the issue still persists.
